### PR TITLE
Adds Redis to docker setup

### PR DESCRIPTION
**Pull request by spikeheap**
Note the `REDIS_AUTH` environment variable isn't honoured by the Redis docker instance, so if it is set to anything other than empty emoncms will fail to connect. This should be remedied by an update to the Redis image, but the quickest solution is probably a custom redis config file. I've run out of time today, but I may take a look at that when I get back.

### CODE REVIEW

**Comment by spikeheap** [comment]
Pah, I accidentally pushed a9c80f0 which I'd intended to do as a separate PR because it relies on https://github.com/emoncms/emoncms/pull/547. If that PR gets merged quickly this could all be done as a single PR, otherwise I'll split it out when I get back from my hols.

**Comment by glynhudson** [comment]
Cheers man! Just had look. As @chaviro says the changes in https://github.com/emoncms/emoncms/pull/547 would be better placed in [process_settings.php](https://github.com/emoncms/emoncms/blob/master/process_settings.php)

I see you have removed installing `git-core\`, is git not needed to enabling git cloning the emoncms repo? 

Ah, I see you have made a bash script to clone dev repos; nice 👍 

Have a good trip

**Comment by spikeheap** [comment]
Hey man, I didn't remove `git-core`, just separated the `apt` and PHP dependency commands, so it's picked up the lack of the `\`. 

Yeah the note on that PR makes sense. I started pulling it across (actually creating a `load_environment_variables.php` to be called from `process_settings.php`, but I'm knee-deep in packing now, should be an easy amendment when I get back.

**Comment by glynhudson** [comment]
Decided to stick with using a `docker.settings.php` file as this gives us more flexibility with the docker setup.  

Redis and repo setup bash script work great. Thanks a lot :+1:

**Pull request merged**
