### PR TITLE
include link to documentation on how to structure the compose file

### PR DESCRIPTION
**Pull request by alexandrecuer**
cf https://community.openenergymonitor.org/t/up-to-date-docker-container-image/27198/10

### CODE REVIEW

**Comment by TrystanLea** [comment]
Thanks @alexandrecuer

**Comment by alexandrecuer** [comment]
Could you please add your docker credits as repository secrets so that the original image can be built by the added workflow when creating a new release ?
you have to go in settings > Security > actions > New repository secrets
then add DOCKER_PASSWORD and DOCKER_USERNAME

**Comment by TrystanLea** [comment]
Thanks Alex, do I enter DOCKER_PASSWORD as the key/name and then in the box the actual password and then the same for username?

image

**Comment by alexandrecuer** [comment]
No it should be in repo secrets cf image

image

image

1)  name : DOCKER_PASSWORD
secret : one of your docker token : glyn must have - he asked me to join your docker organization but i am not an admin so i cant create tokens, admins can create as many token as you want, when you create, you have to note the token somewhere because docker will never be able to tell you the token if you forget it
 
2) name DOCKER_USERNAME
secret : openenergymonitor, ie your docker organization name

it works like that with my user account, never did it with an organization as i dont have any organization account. Now they are not free anymore

**Comment by TrystanLea** [comment]
Sorry for the delay, these are now added

**Comment by alexandrecuer** [comment]
Great now you have to make a release (11.6.9) and it should update the hub :-)

**Comment by TrystanLea** [comment]
Great, what should I put as the release note? https://github.com/emoncms/emoncms-docker/releases/tag/11.6.10

Cheers again!

**Comment by alexandrecuer** [comment]
It seems you have a problem with github actions. It does not want to start...

**Comment by TrystanLea** [comment]
I restarted the job and it seems to have completed now

**Comment by alexandrecuer** [comment]
Note that when publishing the release, you have to keep the same version number you have in the dockerfile
see https://github.com/emoncms/emoncms-docker/blob/9db1d1318c87528385eec1acf8fb4efa1942bfdf/web/Dockerfile#L42
it is 11.6.9 in the dockerfile and you made a 11.6.10 release. the workflow builds its tag from the github release name, not from the version used in the dockerfile.

**Pull request merged**
