### PR TITLE
Mysql stall fix

### PR DESCRIPTION
**Pull request by kronenpj**
MySQL was giving me a very long stall / loop at setting the Timezone. This fixes the probmel I had.

### CODE REVIEW

**Comment by glynhudson** [comment]
Thanks, however there seems to be an issue with this PR. Git is showing zero files changed. Could you double check?

**Comment by kronenpj** [comment]
I’m git challenged... I’ll try again. 😋

**Review by kronenpj — COMMENTED** [review]
Feel free to squash these commits. 😋

**Comment by glynhudson** [comment]
Thanks a lot, sorry it took so long to merge this!

**Pull request merged**
