### PR TITLE
Switched to PHP 7.0 and added basic MQTT support (publish to MQTT only)

### PR DESCRIPTION
**Pull request by janecker**
I switched the base image to PHP 7 and added basic MQTT support. MQTT is only working for publishing to MQTT yet, but the service for receiving data is not yet added. I have experimented with adding the service, but I cannot test it properly since I am only running IotaWatts with my emoncms installation.

### CODE REVIEW

**Comment by glynhudson** [comment]
That's great. MQTT input to Emoncms will need the MQTT inputs script running: https://github.com/emoncms/emoncms/blob/master/scripts/mqtt_input

However Emoncms should now be able to publish to MQTT. Thanks a lot 👍

**Comment by janecker** [comment]
Yeah, I have played around with that already, but as I said I only have the IotaWatt to play around with. Is there a simple way to test if the mqtt inputs are working? Do I only have to send a simple message to a specific topic?

**Comment by glynhudson** [comment]
To test, just send an input to the base topic e.g. if the base topic is `emon` (default). Base topic if set in `settings.php`

`emon/<nodename>/<keyname>   VALUE`

e.g

`emon/emontx/power1 100`

would result in a `100W` input from `emontx` node with key name `power1`

https://guide.openenergymonitor.org/technical/mqtt

**Comment by janecker** [comment]
Ok tried that with a very dirty init.d implementation and it worked. I raised a new issue to discuss how this should be implemented.

**Pull request merged**
